; Saved by version: 2.6.0

[QItemPruebaCuina]
itemname=ItemUniquePhotographicEvidence
starting=False

[QItemLinterna]
itemname=ItemCommonBullseyeLantern
starting=True

[QItemCosa_o_Libro]
itemname=ItemCommonDynamite ItemCommonBandages ItemUniqueHandcuffs ItemCommonBrassKnuckles ItemCommonFlareGun ItemUniqueRope ItemUniquePuzzleBox ItemCommonWhiskey ItemCommonLuckyCigaretteCase
starting=False
traitpool=tome equipment

[QItemLlibre]
starting=False
traits=tome

[QItemDagaRitual]
itemname=ItemCommonRitualDagger
starting=False
inspect=EventDagaLook

[QItemArmaFoc]
itemname=ItemCommonTommyGun
starting=False
traitpool=firearm

[QItemHechizoAtaque]
starting=False
traits=spellattack

[QItemLlavePlata]
itemname=ItemUniqueSilverKey
starting=False

[QItemClausFamilia]
itemname=ItemUniqueOldKeys
starting=True

[QItemArmaFilo]
itemname=ItemCommonRitualDagger ItemCommonMachete
starting=False
traits=bladedweapon

[QItemDiario]
itemname=ItemUniqueOldJournal
starting=False
inspect=EventDiario

[QItemPitillera]
itemname=ItemCommonLuckyCigaretteCase
starting=False

[QItemPruebaAlfombra]
itemname=ItemUniqueCircumstantialEvidence
starting=False

[QItemArconObjetoEquipo]
starting=False
traits=common equipment

[QItemEquipo]
starting=False
traits=common

[QItemWCVendas]
itemname=ItemCommonBandages
starting=False

[QItemLuz]
starting=False
traits=lightsource

[QItemPruebaCarta]
itemname=ItemUniqueConclusiveEvidence
starting=False
inspect=EventRoom2Carta

[QItemPalanca]
itemname=ItemCommonCrowbar
starting=False

[QItemWhiskey]
itemname=ItemCommonWhiskey
starting=False

[QItemHerramienta]
starting=False
traits=heavyweapon

[QItemPruebaMesa]
itemname=ItemUniqueRitualComponents
starting=False

[QItemPruebaTomba]
itemname=ItemUniqueForensicEvidence
starting=False

[QItemMasEquipo]
starting=False
traitpool=heavyweapon equipment

[QItemObjetoEspejo]
itemname=ItemCommonTommyGun
starting=False
traitpool=firearm spelldefence
