; Saved by version: 2.6.0

[CustomMonster_EspectroHenry]
base=MonsterGhost
traits=spirit fleshless
image=Henry_ghost.png
imageplace=motruoFelix.png
health=1
healthperhero=2

[CustomMonster_Mama_Bruixa]
base=MonsterWitch
traits=humanoid
image=bruixa.png
imageplace=bruixa.png
health=4
healthperhero=6
