; Saved by version: 2.6.0

[PuzzleBiblioQuadre]
display=false
buttons=1
event1=EventBiblioQuadreResolt
class=image
skill={lore}
image=Xiuhtecuhtli.jpg
puzzlelevel=3
puzzlealtlevel=2

[PuzzleHallCaixaLlum]
display=false
buttons=1
event1=EventHallAdModulos
quota=3
skill={lore}
puzzlelevel=3
