; Saved by version: 2.6.0
[Quest]
format=18
hidden=False
type=MoM
defaultlanguage=Spanish
defaultmusicon=True
packs=MoM1EM MoM1ET
difficulty=0.6
lengthmin=120
lengthmax=190
image=bolamonster.jpg
version=DD-23-A6-B9-BF-47-8C-91-9A-BF-A8-35-A6-CD-96-E3-96-9F-6D-96-A5-13-08-62-6A-5F-7B-FE-1F-30-14-FF


[QuestText]
Localization.Spanish.txt

[QuestData]
tiles.ini
tokens.ini
events.ini
items.ini
ui.ini
puzzles.ini
spawns.ini
monsters.ini
