; Saved by version: 2.6.0

[SpawnFantasmaDespatx]
xposition=9.33265
yposition=-16.60525
buttons=1
event1=
audio=AudioMonsterGeneric1
monster=CustomMonster_EspectroHenry

[SpawnTio]
xposition=-5.25
yposition=-15.75
operations=TioDescubierto,=,1 ActivaBruja,=,#round ActivaBruja,+,1
buttons=1
event1=
remove=TokenAltarTio
audio=homecridacurt.ogg
monster=MonsterPriestOfDagon
uniquehealth=1
uniquehealthhero=2

[SpawnMama]
xposition=-8.75
yposition=-15.75
vartests=VarOperation:MamaMuerta,==,0 
buttons=1
event1=
remove=TokenAltarMama
audio=AudioMonsterGeneric1
monster=CustomMonster_Mama_Bruixa

[SpawnZombieCripta]
xposition=-16.44241
yposition=-5.373769
operations=CriptaZombi,=,1
vartests=VarOperation:CriptaZombi,==,0 
buttons=1
event1=
audio=zombi.ogg
monster=MonsterZombie
uniquehealth=-2
uniquehealthhero=1

[SpawnRuidoProfundoCuina]
xposition=0.1880376
yposition=-8.603772
buttons=1
event1=
monster=MonsterDeepOneHybrid

[SpawnProfundoDespensa]
xposition=-2.095619
yposition=-4.72087
buttons=1
event1=EventProfundoAvanza
monster=MonsterDeepOne

[SpawnProfundoSotano]
xposition=-1.677984
yposition=-2.493989
buttons=1
event1=EventProfundoAvanza
monster=MonsterDeepOne
uniquehealthhero=1

[SpawnProfundoPont]
xposition=-4.828135
yposition=-12.32117
buttons=1
event1=
monster=MonsterDeepOne
uniquehealthhero=1

[SpawnZombieAltar]
xposition=-6.805623
yposition=-15.68787
buttons=1
event1=
remove=TokenAltarMesa
audio=zombi.ogg
monster=MonsterZombie

[SpawnShoggoth]
xposition=-9.145584
yposition=-15.85054
buttons=1
event1=
monster=MonsterShoggoth
uniquehealth=12
uniquehealthhero=4

[SpawnActivaEspectroHenry]
xposition=0
yposition=0
display=false
buttons=0
monster=CustomMonster_EspectroHenry

[SpawnProfundo_Pasillo]
xposition=4.31294
yposition=-12.19696
buttons=1
event1=
monster=MonsterDeepOneHybrid
