; Saved by version: 2.6.0

[TokenCovaExplPont]
xposition=-5.25
yposition=-7
buttons=1
event1=EventPontAdPont
type=TokenExplore

[TokenSotanInteraccion]
xposition=-2.888
yposition=-5.111677
buttons=1
event1=EventSotanAction_Primer EventSotanSecret
type=TokenInteract

[TokenPontExplAltar]
xposition=-5.25
yposition=-14
buttons=1
event1=EventCovaExplAltar
type=TokenExplore

[TokenInvestigadors]
xposition=12.25
yposition=-12.25
display=false
buttons=0
type=TokenInvestigators

[TokenMuroHall]
xposition=12.25
yposition=-10.5
display=false
buttons=0
type=TokenWallInsideGreen

[TokenMurHallQuadre]
xposition=8.75
yposition=-14
display=false
buttons=0
type=TokenWallInside
rotation=180

[TokenBiblioQuadre]
xposition=1.754645
yposition=-17.01162
buttons=1
event1=EventBiblioQuadreMirar
type=TokenSearch

[TokenBiblioQuadreSecret]
xposition=1.757229
yposition=-17.25432
buttons=1
event1=PuzzleBiblioQuadre
type=TokenInteract

[TokenHallExplRoom]
xposition=8.75
yposition=-10.5
buttons=1
event1=EventAdRoom
type=TokenExplore

[TokenHall_Vista]
xposition=7
yposition=-12.25
buttons=1
event1=EventHallVistaAd
type=TokenSight

[TokenRoomMesita]
xposition=8.037151
yposition=-7.694346
buttons=1
event1=EventRoomInvestigaTauleta
type=TokenSearch

[TokenRoomLlit]
xposition=13.01991
yposition=-9.564242
buttons=1
event1=EventRoomLlit
type=TokenSearch

[TokenHallExploDespatx]
xposition=12.25
yposition=-14
buttons=1
event1=EventHallAdDespatx
audio=AudioPapers2
type=TokenExplore

[TokenBiblioMur]
xposition=1.75
yposition=-17.5
display=false
buttons=0
type=TokenWallInside
rotation=180

[TokenComedorMuro]
xposition=-3.5
yposition=-12.25
display=false
buttons=0
type=TokenWallInsideGreen
rotation=90

[TokenAltarMur]
xposition=-3.5
yposition=-15.75
display=false
buttons=0
type=TokenWallOutsideGreen
rotation=270

[TokenCuinaTrampillaSecreta]
xposition=1.75
yposition=-7
display=false
buttons=0
type=TokenTrapdoor

[TokenHallCaixa]
xposition=13.40359
yposition=-11.01155
buttons=1
event1=PuzzleHallCaixaLlum
type=TokenInteract

[TokenPasilloExplMenjador]
xposition=3.5
yposition=-12.25
buttons=1
event1=EventPasilloAdMenjador
type=TokenExplore

[TokenPasilloVista]
xposition=5.25
yposition=-7
buttons=1
event1=EventPasilloAdEsquina
type=TokenSight

[TokenDespatxExploPorta]
xposition=7
yposition=-15.75
buttons=2
event1=EventDespatxPortaTeclau EventDespatxPortaSenseClau
event2=EventDespatxPortaSenseClau
type=TokenExplore

[TokenBiblioCadira]
xposition=0.9743165
yposition=-15.47555
buttons=1
event1=EventBiblioCadiraUllada
type=TokenSearch

[TokenComedorTaula]
xposition=0.5819775
yposition=-11.73146
buttons=1
event1=EventComedorTaula
type=TokenSearch

[TokenComedorCalaix]
xposition=-2.560032
yposition=-12.17719
buttons=1
event1=EventMenjadorArmari
type=TokenSearch

[TokenComedorExplPortaCuina]
xposition=-1.75
yposition=-10.5
buttons=1
event1=EventCuinaExplo
type=TokenExplore

[TokenEsquinaExplBany]
xposition=8.711858
yposition=-3.212662
buttons=1
event1=EventBanyoAdObs
type=TokenExplore

[TokenEsquinaExplRoom2]
xposition=10.5
yposition=-1.75
buttons=1
event1=EventRoom2Expl
type=TokenExplore

[TokenRoom2ExplArmari]
xposition=12.21932
yposition=-4.597661
buttons=1
event1=EventRoom2Armario
type=TokenExplore

[TokenCuinaExplRebost]
xposition=0.979998
yposition=-8.944929
buttons=1
event1=EventCuinaAdRebost
type=TokenExplore

[TokenPasilloMuro]
xposition=7
yposition=-8.75
display=false
buttons=0
type=TokenWallInside
rotation=270

[TokenCovaExpCripta]
xposition=-10.5
yposition=-5.25
buttons=1
event1=EventCovaLosa
type=TokenExplore

[TokenCuinaTerra]
xposition=-1.75
yposition=-8.75
buttons=1
event1=EventCuinaTerra EventCuinaTerraObserva
type=TokenSearch

[TokenCuinaCalaix]
xposition=-0.2062616
yposition=-10.12614
buttons=1
event1=EventCuinaCalaix
type=TokenSearch

[TokenDespatxTaula]
xposition=9.430075
yposition=-15.95671
buttons=1
event1=EventDespatxTaulaPassat
quota=2
type=TokenSearch

[TokenDespatxLlibres]
xposition=12.26558
yposition=-16.81544
buttons=1
event1=EventDespatxPared
type=TokenSearch

[TokenRoomMuro]
xposition=7
yposition=-8.75
display=false
buttons=0
type=TokenWallInside
rotation=90

[TokenPasilloTauleta]
xposition=5.601307
yposition=-13.46297
buttons=1
event1=EventPasilloTauleta
type=TokenSearch

[TokenBiblioA_EstanteDcha]
xposition=4.682134
yposition=-14.51023
buttons=1
event1=EventBiblioA_0EstanteDcha
type=TokenSearch

[TokenEsquinaEspejo]
xposition=4.12933
yposition=-4.660286
buttons=1
event1=EventEsquinaEspejoLook
type=TokenSearch

[TokenEsquinaCatifa]
xposition=8.75
yposition=-1.75
buttons=1
event1=EventEsquinaCatifa
type=TokenSearch

[TokenEsquinaPuertaRoom2]
xposition=10.5
yposition=-1.75
display=false
buttons=0
type=TokenDoorInside
rotation=270

[TokenCuinaAlmacenAcccion]
xposition=2.043666
yposition=-7.868561
buttons=1
event1=EventAlmacenAdPasadizo
type=TokenInteract

[TokenSotanFosc1]
xposition=0.5729609
yposition=-4.883078
display=false
buttons=0
type=TokenDarkness
rotation=270

[TokenHallCuadro]
xposition=8.764403
yposition=-13.49184
buttons=1
event1=EventHallCuadro
type=TokenSearch

[TokenCuinaArca]
xposition=2.810174
yposition=-9.482909
buttons=1
event1=EventCuinaArcon EventCuinaArconSuperat
type=TokenSearch

[TokenWCBanyera]
xposition=9.418076
yposition=-6.031752
buttons=1
event1=EventWCBanyera
type=TokenSearch

[TokenSotanFosc2]
xposition=2.508512
yposition=-2.25885
display=false
buttons=0
type=TokenDarkness
rotation=270

[TokenSotanFosc3]
xposition=-1.591049
yposition=-6.102639
display=false
buttons=0
type=TokenDarkness
rotation=270

[TokenSotanMur]
xposition=1.75
yposition=0
display=false
buttons=0
type=TokenWallOutsideGreen

[TokenSotanMurMoble]
xposition=-3.509632
yposition=-5.211255
display=false
buttons=0
type=TokenWallInsideGreen
rotation=90

[TokenSotanMurPasadis]
xposition=-3.07121
yposition=-5.111388
buttons=1
event1=
type=TokenSecretOutside
rotation=90

[TokenSotanExplEscala]
xposition=1.75
yposition=-3.5
buttons=1
event1=EventSotanEscala
type=TokenExplore

[TokenRoom2Llit]
xposition=12.94887
yposition=-0.8934624
buttons=1
event1=EventRoom2Llit
type=TokenSearch

[TokenRoom2ArmariFosc]
xposition=11.83533
yposition=-5.975167
display=false
buttons=0
type=TokenDarkness
rotation=270

[TokenRoom2ArmariCaja]
xposition=12.7158
yposition=-5.779935
buttons=1
event1=EventRoom2ArmariCaja
type=TokenSearch

[TokenSotanBagul]
xposition=0.1010991
yposition=-0.7723166
buttons=1
event1=EventSotanBagul
type=TokenSearch

[TokenSotanExplDespensa]
xposition=-1.75
yposition=-3.5
buttons=1
event1=EventSotanPorta
type=TokenExplore

[TokenSotanObstacle]
xposition=-0.6531677
yposition=-2.867226
display=false
buttons=0
type=TokenBarricadeInside
rotation=180

[TokenSotanTrastos]
xposition=-2.270459
yposition=-1.357186
buttons=1
event1=EventSotanTrastos
type=TokenSearch

[TokenSotanDespensaTerra]
xposition=-1.558743
yposition=-4.742376
buttons=1
event1=EventSotanDespensaTerra
type=TokenSearch

[TokenPont]
xposition=-5.398018
yposition=-9.720209
buttons=1
event1=EventPont
type=TokenSearch

[TokenCovaDibuix]
xposition=-7.855231
yposition=-4.023112
buttons=1
event1=EventCovaDibuix
type=TokenSearch

[TokenAltarMama]
xposition=-8.606505
yposition=-15.8938
buttons=2
event1=EventMama
event2=EventMamaPlease
type=TokenOrangeWoman

[TokenAltarTio]
xposition=-5.014936
yposition=-15.89718
buttons=2
event1=EventTioHablar
event2=EventTioPara
type=TokenWhiteMan

[TokenAltarPortal]
xposition=-10.17381
yposition=-15.76969
buttons=1
event1=EventAltarPortal
type=TokenInteract

[TokenAltarMesa]
xposition=-6.888856
yposition=-15.83332
buttons=1
event1=EventAltarMesa
type=TokenSearch

[TokenCriptaOscuridad]
xposition=-14.32648
yposition=-5.225012
display=false
buttons=0
type=TokenDarkness
rotation=270

[TokenCriptaTomba]
xposition=-12.79593
yposition=-5.328844
buttons=3
event1=EventCriptaTomba2
event2=EventCriptaTomba1
event3=EventCriptaTombaFallo
type=TokenSearch

[TokenObjetivo]
xposition=13.44092
yposition=-12.24368
buttons=1
event1=EventxObjetivoCumplidoHeroes EventxObjetivoCumplidoHeroes2
type=TokenInteract

[TokenEsquinaEspejoAccion]
xposition=4.079207
yposition=-4.782812
buttons=1
event1=EventEsquinaEspejoAgujeroSICruz EventEsquinaEspejoNoCruzSiDaga EventEsquinaEspejoAgujeroNODaga
type=TokenInteract

[TokenRoom2Carta]
xposition=11.08831
yposition=-6.34904
buttons=1
event1=EventRoom2CartaRecoge
type=TokenSearch

[TokenCriptaFondo]
xposition=-17.5
yposition=-5.25
display=false
buttons=1
event1=EventCriptaFondoTest
type=TokenSight

[TokenComedorObstruccion]
xposition=-2.566661
yposition=-10.98485
display=false
buttons=0
type=TokenBarricadeInside

[TokenEsquinaHuecoVista]
xposition=5.558529
yposition=-2.119188
buttons=1
event1=EventEsquinaHuecoPuerta
type=TokenSight
