; Saved by version: 3.24 MAJOR
[Quest]
format=21
hidden=False
type=MoM
defaultlanguage=Spanish
defaultmusicon=True
packs=MoM1EM MoM1ET
difficulty=0.6
lengthmin=120
lengthmax=190
image=bolamonster.jpg
version=3C-5A-D6-70-E8-E0-1F-1F-11-B7-C2-E0-B7-BC-EA-7E-39-EC-1A-30-F6-B8-F3-87-77-71-85-76-32-4E-2A-EE


[QuestText]
Localization.Spanish.txt
Localization.French.txt

[QuestData]
tiles.ini
tokens.ini
events.ini
items.ini
ui.ini
puzzles.ini
spawns.ini
monsters.ini
